### ISSUE TITLE
linux command line - multipleshells

### ISSUE THREAD

**Issue by prof-braino** [salsanci/YRShell#15]
First time thru multipleshells, the OK> shell prompt overwrites the version/commit string:

yrshell@yrshell-VirtualBox ~/YRShell.20171027/build $ ./yrshell

YRShell Version 0.2  commit: 0f2d8750fdc8fd5b3c189acb879ddf90710340bf [0f2d875]
bShell>

bShell>>>>
>>>

YRShell Version 0.2  commit: 0f2d8750fdc8fd5b3c189acb879ddf90710340bf [0f2d875]
HELO>>>>
>>>

[error is in the following line]

YRShell Version 0.2  commit: 0f2d8750fdc8fd5b3c189acb879ddfOK>>>>
>>>
bShell>>>>
>>>
HELO>>>>
>>>
OK>>>>
>>>
bShell>>>>
>>>
HELO>>>>
>>>
OK>

**Comment by salsanci** [comment]
fixed
