### ISSUE TITLE
virtualbox Windows 10 client

### ISSUE THREAD

**Issue by prof-braino** [salsanci/YRShell#4]
Do I need to install gcc for windows 10 to compile yrshell.cpp?

**Comment by prof-braino** [comment]
In windows 10, need to enable the linux features.  The developer thing.
CAREFUL,  it might use visual c instead of GCC.

**Comment by prof-braino** [comment]
Enabling Ubuntu subsystem appears to break folder sharing between host and client.  The host shared folders are no longer visible in Windows 10.  
Workaround: enable bidirectional drag and drop between host and client.

**Comment by prof-braino** [comment]
BASH for windows 10 with build-essential

YRShell1607test@DESKTOP-V1OFTOJ:/mnt/c/Users/YRShell/Documents/Arduino/libraries/YRShell-master-20171022/build$ make
g++ -pthread  -c -o testSupport.o testSupport.cpp -I . -I /usr/include -std=c++11 -O3
In file included from ../YRShell.h:7:0,
                 from testSupport.h:3,
                 from testSupport.cpp:2:
../utility/YRShellInterpreter.h: In member function ‘bool ShellRunner::init()’:
../utility/YRShellInterpreter.h:262:18: error: ‘virtual void YRShellInterpreter::init()’ is protected
     virtual void init( void);
                  ^
testSupport.cpp:9:18: error: within this context
     m_shell.init();
                  ^
Makefile:18: recipe for target 'testSupport.o' failed
make: *** [testSupport.o] Error 1
YRShell1607test@DESKTOP-V1OFTOJ:/mnt/c/Users/YRShell/Documents/Arduino/libraries/YRShell-master-20171022/build$

**Comment by salsanci** [comment]
I think this is an old commit. Can you please pull down the most recent and retry.

**Comment by prof-braino** [comment]
Works using WLS (bash for windows 10).  
executes from BASH command line, 
does not execute from windows 10 command prompt
