### ISSUE TITLE
testShell line 85                    //digitalWrite(LED_BUILTIN, HIGH);

### ISSUE THREAD

**Issue by prof-braino** [salsanci/YRShell#6]
Is it intentional that the actions in ledOn and ledOff are commented out?
            case SE_CC_ledOn:
                if( ledControl) {
                    //digitalWrite(LED_BUILTIN, HIGH);
                }

Is removing the comment intended to be and exercise for the user?
            case SE_CC_ledOn:
                if( ledControl) {
                    //digitalWrite(LED_BUILTIN, HIGH);
                    digitalWrite(LED_BUILTIN, HIGH);
                }

If so, please consider stating this in the doxygen comments.

**Comment by salsanci** [comment]
fixed
