### ISSUE TITLE
multipleshells.ino - odd prompt first time thru shells

### ISSUE THREAD

**Issue by prof-braino** [salsanci/YRShell#7]
It looks like switching to the odd number shells has an extra string the first time thru, 
C:\Users\YRShell\Documents\Arduino\lib
Maybe its an initialization oversight?

Step1: load BLINK.ino example
Step2: load multipleshells.ino

YRShell Version 0.2
YR_000>
YR_000>
YR_000>>>>

YRShell Version 0.2
C:\Users\YRShell\Documents\Arduino\libYR_001>
YR_001>
YR_001>>>>

YRShell Version 0.2
YR_002>>>>

YRShell Version 0.2
C:\Users\YRShell\Documents\Arduino\libYR_003>>>>
YR_000>>>>
YR_001>>>>
YR_002>>>>
YR_003>>>>
YR_000>

**Comment by salsanci** [comment]
Output queue of small shell was too small (64), increasing to 90.
